//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.08 at 03:02:05 PM PST 
//


package com.wb.nextgen.md.schema.v2_3;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import org.w3c.dom.Element;


/**
 * <p>Java class for CompObjEntry-type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CompObjEntry-type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="DisplayName" type="{http://www.movielabs.com/schema/md/v2.3/md}StringAndLanguage-type" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="EntryNumber" type="{http://www.movielabs.com/schema/md/v2.3/md}string-Compilation-EntryNumber" minOccurs="0"/&gt;
 *         &lt;element name="EntryClass" type="{http://www.movielabs.com/schema/md/v2.3/md}string-Compilation-EntryClass" minOccurs="0"/&gt;
 *         &lt;element name="Entry" type="{http://www.movielabs.com/schema/md/v2.3/md}CompObjEntry-type" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;choice&gt;
 *           &lt;element name="ContentID" type="{http://www.movielabs.com/schema/md/v2.3/md}ContentID-type"/&gt;
 *           &lt;element name="BasicMetadata" type="{http://www.movielabs.com/schema/md/v2.3/md}BasicMetadata-type"/&gt;
 *           &lt;any processContents='lax' namespace='##other'/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CompObjEntry-type", propOrder = {
    "displayName",
    "entryNumber",
    "entryClass",
    "entry",
    "contentID",
    "basicMetadata",
    "any"
})
public class CompObjEntryType {

    @XmlElement(name = "DisplayName")
    protected List<StringAndLanguageType> displayName;
    @XmlElement(name = "EntryNumber")
    protected String entryNumber;
    @XmlElement(name = "EntryClass")
    protected String entryClass;
    @XmlElement(name = "Entry")
    protected List<CompObjEntryType> entry;
    @XmlElement(name = "ContentID")
    @XmlSchemaType(name = "anyURI")
    protected String contentID;
    @XmlElement(name = "BasicMetadata")
    protected BasicMetadataType basicMetadata;
    @XmlAnyElement(lax = true)
    protected Object any;

    /**
     * Gets the value of the displayName property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the displayName property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDisplayName().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StringAndLanguageType }
     * 
     * 
     */
    public List<StringAndLanguageType> getDisplayName() {
        if (displayName == null) {
            displayName = new ArrayList<StringAndLanguageType>();
        }
        return this.displayName;
    }

    /**
     * Gets the value of the entryNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntryNumber() {
        return entryNumber;
    }

    /**
     * Sets the value of the entryNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntryNumber(String value) {
        this.entryNumber = value;
    }

    /**
     * Gets the value of the entryClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntryClass() {
        return entryClass;
    }

    /**
     * Sets the value of the entryClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntryClass(String value) {
        this.entryClass = value;
    }

    /**
     * Gets the value of the entry property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the entry property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEntry().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CompObjEntryType }
     * 
     * 
     */
    public List<CompObjEntryType> getEntry() {
        if (entry == null) {
            entry = new ArrayList<CompObjEntryType>();
        }
        return this.entry;
    }

    /**
     * Gets the value of the contentID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContentID() {
        return contentID;
    }

    /**
     * Sets the value of the contentID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContentID(String value) {
        this.contentID = value;
    }

    /**
     * Gets the value of the basicMetadata property.
     * 
     * @return
     *     possible object is
     *     {@link BasicMetadataType }
     *     
     */
    public BasicMetadataType getBasicMetadata() {
        return basicMetadata;
    }

    /**
     * Sets the value of the basicMetadata property.
     * 
     * @param value
     *     allowed object is
     *     {@link BasicMetadataType }
     *     
     */
    public void setBasicMetadata(BasicMetadataType value) {
        this.basicMetadata = value;
    }

    /**
     * Gets the value of the any property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     {@link Element }
     *     
     */
    public Object getAny() {
        return any;
    }

    /**
     * Sets the value of the any property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     {@link Element }
     *     
     */
    public void setAny(Object value) {
        this.any = value;
    }

}
