//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.08 at 03:02:05 PM PST 
//


package com.wb.nextgen.md.schema.v2_3;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CompObj-type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CompObj-type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Entry" type="{http://www.movielabs.com/schema/md/v2.3/md}CompObjEntry-type" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="CompilationClass" type="{http://www.movielabs.com/schema/md/v2.3/md}CompObjClass-type" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CompObj-type", propOrder = {
    "entry",
    "compilationClass"
})
@XmlSeeAlso({
    CompObjDataType.class
})
public class CompObjType {

    @XmlElement(name = "Entry")
    protected List<CompObjEntryType> entry;
    @XmlElement(name = "CompilationClass")
    protected CompObjClassType compilationClass;

    /**
     * Gets the value of the entry property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the entry property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEntry().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CompObjEntryType }
     * 
     * 
     */
    public List<CompObjEntryType> getEntry() {
        if (entry == null) {
            entry = new ArrayList<CompObjEntryType>();
        }
        return this.entry;
    }

    /**
     * Gets the value of the compilationClass property.
     * 
     * @return
     *     possible object is
     *     {@link CompObjClassType }
     *     
     */
    public CompObjClassType getCompilationClass() {
        return compilationClass;
    }

    /**
     * Sets the value of the compilationClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link CompObjClassType }
     *     
     */
    public void setCompilationClass(CompObjClassType value) {
        this.compilationClass = value;
    }

}
