//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.08 at 03:02:05 PM PST 
//


package com.wb.nextgen.md.schema.v2_3;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ContainerMetadataWithID-type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ContainerMetadataWithID-type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.movielabs.com/schema/md/v2.3/md}ContainerMetadata-type"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ContainerID" type="{http://www.movielabs.com/schema/md/v2.3/md}ContentIdentifier-type"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ContainerMetadataWithID-type", propOrder = {
    "containerID"
})
public class ContainerMetadataWithIDType
    extends ContainerMetadataType
{

    @XmlElement(name = "ContainerID", required = true)
    protected ContentIdentifierType containerID;

    /**
     * Gets the value of the containerID property.
     * 
     * @return
     *     possible object is
     *     {@link ContentIdentifierType }
     *     
     */
    public ContentIdentifierType getContainerID() {
        return containerID;
    }

    /**
     * Sets the value of the containerID property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContentIdentifierType }
     *     
     */
    public void setContainerID(ContentIdentifierType value) {
        this.containerID = value;
    }

}
