//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.08 at 03:02:05 PM PST 
//


package com.wb.nextgen.md.schema.v2_3;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ContentSequenceInfo-type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ContentSequenceInfo-type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Number" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="DistributionNumber" type="{http://www.movielabs.com/schema/md/v2.3/md}complex-SequenceInfo-DistributionNumber" minOccurs="0"/&gt;
 *         &lt;element name="HouseSequence" type="{http://www.movielabs.com/schema/md/v2.3/md}complex-SequenceInfo-HouseSequence" minOccurs="0"/&gt;
 *         &lt;element name="AlternateNumber" type="{http://www.movielabs.com/schema/md/v2.3/md}complex-SequenceInfo-AlternateNumber" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ContentSequenceInfo-type", propOrder = {
    "number",
    "distributionNumber",
    "houseSequence",
    "alternateNumber"
})
public class ContentSequenceInfoType {

    @XmlElement(name = "Number")
    protected Integer number;
    @XmlElement(name = "DistributionNumber")
    protected ComplexSequenceInfoDistributionNumber distributionNumber;
    @XmlElement(name = "HouseSequence")
    protected ComplexSequenceInfoHouseSequence houseSequence;
    @XmlElement(name = "AlternateNumber")
    protected List<ComplexSequenceInfoAlternateNumber> alternateNumber;

    /**
     * Gets the value of the number property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * Sets the value of the number property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNumber(Integer value) {
        this.number = value;
    }

    /**
     * Gets the value of the distributionNumber property.
     * 
     * @return
     *     possible object is
     *     {@link ComplexSequenceInfoDistributionNumber }
     *     
     */
    public ComplexSequenceInfoDistributionNumber getDistributionNumber() {
        return distributionNumber;
    }

    /**
     * Sets the value of the distributionNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComplexSequenceInfoDistributionNumber }
     *     
     */
    public void setDistributionNumber(ComplexSequenceInfoDistributionNumber value) {
        this.distributionNumber = value;
    }

    /**
     * Gets the value of the houseSequence property.
     * 
     * @return
     *     possible object is
     *     {@link ComplexSequenceInfoHouseSequence }
     *     
     */
    public ComplexSequenceInfoHouseSequence getHouseSequence() {
        return houseSequence;
    }

    /**
     * Sets the value of the houseSequence property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComplexSequenceInfoHouseSequence }
     *     
     */
    public void setHouseSequence(ComplexSequenceInfoHouseSequence value) {
        this.houseSequence = value;
    }

    /**
     * Gets the value of the alternateNumber property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the alternateNumber property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAlternateNumber().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ComplexSequenceInfoAlternateNumber }
     * 
     * 
     */
    public List<ComplexSequenceInfoAlternateNumber> getAlternateNumber() {
        if (alternateNumber == null) {
            alternateNumber = new ArrayList<ComplexSequenceInfoAlternateNumber>();
        }
        return this.alternateNumber;
    }

}
