//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.08 at 03:02:05 PM PST 
//


package com.wb.nextgen.md.schema.v2_3;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DigitalAssetSet-type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DigitalAssetSet-type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Audio" type="{http://www.movielabs.com/schema/md/v2.3/md}DigitalAssetAudioData-type" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="Video" type="{http://www.movielabs.com/schema/md/v2.3/md}DigitalAssetVideoData-type" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="Subtitle" type="{http://www.movielabs.com/schema/md/v2.3/md}DigitalAssetSubtitleData-type" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="Image" type="{http://www.movielabs.com/schema/md/v2.3/md}DigitalAssetImageData-type" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="Interactive" type="{http://www.movielabs.com/schema/md/v2.3/md}DigitalAssetInteractiveData-type" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="Ancillary" type="{http://www.movielabs.com/schema/md/v2.3/md}DigitalAssetAncillaryData-type" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DigitalAssetSet-type", propOrder = {
    "audio",
    "video",
    "subtitle",
    "image",
    "interactive",
    "ancillary"
})
public class DigitalAssetSetType {

    @XmlElement(name = "Audio")
    protected List<DigitalAssetAudioDataType> audio;
    @XmlElement(name = "Video")
    protected List<DigitalAssetVideoDataType> video;
    @XmlElement(name = "Subtitle")
    protected List<DigitalAssetSubtitleDataType> subtitle;
    @XmlElement(name = "Image")
    protected List<DigitalAssetImageDataType> image;
    @XmlElement(name = "Interactive")
    protected List<DigitalAssetInteractiveDataType> interactive;
    @XmlElement(name = "Ancillary")
    protected List<DigitalAssetAncillaryDataType> ancillary;

    /**
     * Gets the value of the audio property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the audio property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAudio().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DigitalAssetAudioDataType }
     * 
     * 
     */
    public List<DigitalAssetAudioDataType> getAudio() {
        if (audio == null) {
            audio = new ArrayList<DigitalAssetAudioDataType>();
        }
        return this.audio;
    }

    /**
     * Gets the value of the video property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the video property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVideo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DigitalAssetVideoDataType }
     * 
     * 
     */
    public List<DigitalAssetVideoDataType> getVideo() {
        if (video == null) {
            video = new ArrayList<DigitalAssetVideoDataType>();
        }
        return this.video;
    }

    /**
     * Gets the value of the subtitle property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the subtitle property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSubtitle().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DigitalAssetSubtitleDataType }
     * 
     * 
     */
    public List<DigitalAssetSubtitleDataType> getSubtitle() {
        if (subtitle == null) {
            subtitle = new ArrayList<DigitalAssetSubtitleDataType>();
        }
        return this.subtitle;
    }

    /**
     * Gets the value of the image property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the image property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getImage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DigitalAssetImageDataType }
     * 
     * 
     */
    public List<DigitalAssetImageDataType> getImage() {
        if (image == null) {
            image = new ArrayList<DigitalAssetImageDataType>();
        }
        return this.image;
    }

    /**
     * Gets the value of the interactive property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the interactive property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInteractive().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DigitalAssetInteractiveDataType }
     * 
     * 
     */
    public List<DigitalAssetInteractiveDataType> getInteractive() {
        if (interactive == null) {
            interactive = new ArrayList<DigitalAssetInteractiveDataType>();
        }
        return this.interactive;
    }

    /**
     * Gets the value of the ancillary property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ancillary property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAncillary().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DigitalAssetAncillaryDataType }
     * 
     * 
     */
    public List<DigitalAssetAncillaryDataType> getAncillary() {
        if (ancillary == null) {
            ancillary = new ArrayList<DigitalAssetAncillaryDataType>();
        }
        return this.ancillary;
    }

}
