//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.08 at 03:02:05 PM PST 
//


package com.wb.nextgen.md.schema.v2_3;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for DigitalAssetVideoPictureLightLevel-type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DigitalAssetVideoPictureLightLevel-type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ContentMax" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;simpleContent&gt;
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;nonNegativeInteger"&gt;
 *                 &lt;attribute name="interpretation" type="{http://www.movielabs.com/schema/md/v2.3/md}string-Video-Pic-CMaxInterpretation" /&gt;
 *               &lt;/extension&gt;
 *             &lt;/simpleContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="FrameAverageMax" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;simpleContent&gt;
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;nonNegativeInteger"&gt;
 *                 &lt;attribute name="interpretation" type="{http://www.movielabs.com/schema/md/v2.3/md}string-Video-Pic-FMaxInterpretation" /&gt;
 *               &lt;/extension&gt;
 *             &lt;/simpleContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DigitalAssetVideoPictureLightLevel-type", propOrder = {
    "contentMax",
    "frameAverageMax"
})
public class DigitalAssetVideoPictureLightLevelType {

    @XmlElement(name = "ContentMax")
    protected List<DigitalAssetVideoPictureLightLevelType.ContentMax> contentMax;
    @XmlElement(name = "FrameAverageMax")
    protected List<DigitalAssetVideoPictureLightLevelType.FrameAverageMax> frameAverageMax;

    /**
     * Gets the value of the contentMax property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the contentMax property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContentMax().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DigitalAssetVideoPictureLightLevelType.ContentMax }
     * 
     * 
     */
    public List<DigitalAssetVideoPictureLightLevelType.ContentMax> getContentMax() {
        if (contentMax == null) {
            contentMax = new ArrayList<DigitalAssetVideoPictureLightLevelType.ContentMax>();
        }
        return this.contentMax;
    }

    /**
     * Gets the value of the frameAverageMax property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the frameAverageMax property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFrameAverageMax().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DigitalAssetVideoPictureLightLevelType.FrameAverageMax }
     * 
     * 
     */
    public List<DigitalAssetVideoPictureLightLevelType.FrameAverageMax> getFrameAverageMax() {
        if (frameAverageMax == null) {
            frameAverageMax = new ArrayList<DigitalAssetVideoPictureLightLevelType.FrameAverageMax>();
        }
        return this.frameAverageMax;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;simpleContent&gt;
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;nonNegativeInteger"&gt;
     *       &lt;attribute name="interpretation" type="{http://www.movielabs.com/schema/md/v2.3/md}string-Video-Pic-CMaxInterpretation" /&gt;
     *     &lt;/extension&gt;
     *   &lt;/simpleContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class ContentMax {

        @XmlValue
        @XmlSchemaType(name = "nonNegativeInteger")
        protected BigInteger value;
        @XmlAttribute(name = "interpretation")
        protected String interpretation;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setValue(BigInteger value) {
            this.value = value;
        }

        /**
         * Gets the value of the interpretation property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getInterpretation() {
            return interpretation;
        }

        /**
         * Sets the value of the interpretation property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setInterpretation(String value) {
            this.interpretation = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;simpleContent&gt;
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;nonNegativeInteger"&gt;
     *       &lt;attribute name="interpretation" type="{http://www.movielabs.com/schema/md/v2.3/md}string-Video-Pic-FMaxInterpretation" /&gt;
     *     &lt;/extension&gt;
     *   &lt;/simpleContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class FrameAverageMax {

        @XmlValue
        @XmlSchemaType(name = "nonNegativeInteger")
        protected BigInteger value;
        @XmlAttribute(name = "interpretation")
        protected String interpretation;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setValue(BigInteger value) {
            this.value = value;
        }

        /**
         * Gets the value of the interpretation property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getInterpretation() {
            return interpretation;
        }

        /**
         * Sets the value of the interpretation property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setInterpretation(String value) {
            this.interpretation = value;
        }

    }

}
