//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.08 at 03:02:05 PM PST 
//


package com.wb.nextgen.md.schema.v2_3;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import com.wb.nextgen.manifest.schema.v1_4.InventoryVideoType;


/**
 * <p>Java class for DigitalAssetVideoData-type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DigitalAssetVideoData-type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Type" type="{http://www.movielabs.com/schema/md/v2.3/md}string-Video-Type" minOccurs="0"/&gt;
 *         &lt;element name="Encoding" type="{http://www.movielabs.com/schema/md/v2.3/md}DigitalAssetVideoEncoding-type" minOccurs="0"/&gt;
 *         &lt;element name="Picture" type="{http://www.movielabs.com/schema/md/v2.3/md}DigitalAssetVideoPicture-type"/&gt;
 *         &lt;element name="ColorType" type="{http://www.movielabs.com/schema/md/v2.3/md}ColorType-type" minOccurs="0"/&gt;
 *         &lt;element name="PictureFormat" type="{http://www.movielabs.com/schema/md/v2.3/md}string-Video-PictureFormat" minOccurs="0"/&gt;
 *         &lt;element name="SubtitleLanguage" type="{http://www.movielabs.com/schema/md/v2.3/md}DigitalAssetVideoSubtitleLanguage-type" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="SignedLanguage" type="{http://www.movielabs.com/schema/md/v2.3/md}language-redefine" minOccurs="0"/&gt;
 *         &lt;element name="CardsetList" type="{http://www.movielabs.com/schema/md/v2.3/md}DigitalAssetCardsetList-type" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="TrackReference" type="{http://www.movielabs.com/schema/md/v2.3/md}string-TrackReference" minOccurs="0"/&gt;
 *         &lt;element name="TrackIdentifier" type="{http://www.movielabs.com/schema/md/v2.3/md}ContentIdentifier-type" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="Private" type="{http://www.movielabs.com/schema/md/v2.3/md}PrivateData-type" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DigitalAssetVideoData-type", propOrder = {
    "description",
    "type",
    "encoding",
    "picture",
    "colorType",
    "pictureFormat",
    "subtitleLanguage",
    "signedLanguage",
    "cardsetList",
    "trackReference",
    "trackIdentifier",
    "_private"
})
@XmlSeeAlso({
    InventoryVideoType.class
})
public class DigitalAssetVideoDataType {

    @XmlElement(name = "Description")
    protected String description;
    @XmlElement(name = "Type")
    protected String type;
    @XmlElement(name = "Encoding")
    protected DigitalAssetVideoEncodingType encoding;
    @XmlElement(name = "Picture", required = true)
    protected DigitalAssetVideoPictureType picture;
    @XmlElement(name = "ColorType")
    @XmlSchemaType(name = "string")
    protected ColorTypeType colorType;
    @XmlElement(name = "PictureFormat")
    protected String pictureFormat;
    @XmlElement(name = "SubtitleLanguage")
    protected List<DigitalAssetVideoSubtitleLanguageType> subtitleLanguage;
    @XmlElement(name = "SignedLanguage")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "language")
    protected String signedLanguage;
    @XmlElement(name = "CardsetList")
    protected List<DigitalAssetCardsetListType> cardsetList;
    @XmlElement(name = "TrackReference")
    protected String trackReference;
    @XmlElement(name = "TrackIdentifier")
    protected List<ContentIdentifierType> trackIdentifier;
    @XmlElement(name = "Private")
    protected PrivateDataType _private;

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the encoding property.
     * 
     * @return
     *     possible object is
     *     {@link DigitalAssetVideoEncodingType }
     *     
     */
    public DigitalAssetVideoEncodingType getEncoding() {
        return encoding;
    }

    /**
     * Sets the value of the encoding property.
     * 
     * @param value
     *     allowed object is
     *     {@link DigitalAssetVideoEncodingType }
     *     
     */
    public void setEncoding(DigitalAssetVideoEncodingType value) {
        this.encoding = value;
    }

    /**
     * Gets the value of the picture property.
     * 
     * @return
     *     possible object is
     *     {@link DigitalAssetVideoPictureType }
     *     
     */
    public DigitalAssetVideoPictureType getPicture() {
        return picture;
    }

    /**
     * Sets the value of the picture property.
     * 
     * @param value
     *     allowed object is
     *     {@link DigitalAssetVideoPictureType }
     *     
     */
    public void setPicture(DigitalAssetVideoPictureType value) {
        this.picture = value;
    }

    /**
     * Gets the value of the colorType property.
     * 
     * @return
     *     possible object is
     *     {@link ColorTypeType }
     *     
     */
    public ColorTypeType getColorType() {
        return colorType;
    }

    /**
     * Sets the value of the colorType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ColorTypeType }
     *     
     */
    public void setColorType(ColorTypeType value) {
        this.colorType = value;
    }

    /**
     * Gets the value of the pictureFormat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPictureFormat() {
        return pictureFormat;
    }

    /**
     * Sets the value of the pictureFormat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPictureFormat(String value) {
        this.pictureFormat = value;
    }

    /**
     * Gets the value of the subtitleLanguage property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the subtitleLanguage property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSubtitleLanguage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DigitalAssetVideoSubtitleLanguageType }
     * 
     * 
     */
    public List<DigitalAssetVideoSubtitleLanguageType> getSubtitleLanguage() {
        if (subtitleLanguage == null) {
            subtitleLanguage = new ArrayList<DigitalAssetVideoSubtitleLanguageType>();
        }
        return this.subtitleLanguage;
    }

    /**
     * Gets the value of the signedLanguage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSignedLanguage() {
        return signedLanguage;
    }

    /**
     * Sets the value of the signedLanguage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSignedLanguage(String value) {
        this.signedLanguage = value;
    }

    /**
     * Gets the value of the cardsetList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cardsetList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCardsetList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DigitalAssetCardsetListType }
     * 
     * 
     */
    public List<DigitalAssetCardsetListType> getCardsetList() {
        if (cardsetList == null) {
            cardsetList = new ArrayList<DigitalAssetCardsetListType>();
        }
        return this.cardsetList;
    }

    /**
     * Gets the value of the trackReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrackReference() {
        return trackReference;
    }

    /**
     * Sets the value of the trackReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrackReference(String value) {
        this.trackReference = value;
    }

    /**
     * Gets the value of the trackIdentifier property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the trackIdentifier property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTrackIdentifier().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ContentIdentifierType }
     * 
     * 
     */
    public List<ContentIdentifierType> getTrackIdentifier() {
        if (trackIdentifier == null) {
            trackIdentifier = new ArrayList<ContentIdentifierType>();
        }
        return this.trackIdentifier;
    }

    /**
     * Gets the value of the private property.
     * 
     * @return
     *     possible object is
     *     {@link PrivateDataType }
     *     
     */
    public PrivateDataType getPrivate() {
        return _private;
    }

    /**
     * Sets the value of the private property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrivateDataType }
     *     
     */
    public void setPrivate(PrivateDataType value) {
        this._private = value;
    }

}
