//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.08 at 03:02:05 PM PST 
//


package com.wb.nextgen.md.schema.v2_3;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for string-DisplayIndicators.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="string-DisplayIndicators"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="CC"/&gt;
 *     &lt;enumeration value="F"/&gt;
 *     &lt;enumeration value="P"/&gt;
 *     &lt;enumeration value="DD"/&gt;
 *     &lt;enumeration value="SAP"/&gt;
 *     &lt;enumeration value="DVS"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "string-DisplayIndicators")
@XmlEnum
public enum StringDisplayIndicators {

    CC,
    F,
    P,
    DD,
    SAP,
    DVS;

    public String value() {
        return name();
    }

    public static StringDisplayIndicators fromValue(String v) {
        return valueOf(v);
    }

}
