//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.08 at 03:02:05 PM PST 
//


package com.wb.nextgen.manifest.schema.v1_4;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import com.wb.nextgen.md.schema.v2_3.BasicMetadataType;


/**
 * <p>Java class for Audiovisual-type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Audiovisual-type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Type" type="{http://www.movielabs.com/schema/manifest/v1.4/manifest}AudiovisualType-string"/&gt;
 *         &lt;element name="SubType" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;choice minOccurs="0"&gt;
 *           &lt;element name="PresentationID" type="{http://www.movielabs.com/schema/manifest/v1.4/manifest}PresentationID-type"/&gt;
 *           &lt;element name="PlayableSequenceID" type="{http://www.movielabs.com/schema/manifest/v1.4/manifest}PlayableSequenceID-type"/&gt;
 *           &lt;element name="PlayableSequence" type="{http://www.movielabs.com/schema/manifest/v1.4/manifest}PlayableSequence-type"/&gt;
 *         &lt;/choice&gt;
 *         &lt;choice minOccurs="0"&gt;
 *           &lt;element name="ContentID" type="{http://www.movielabs.com/schema/md/v2.3/md}ContentID-type"/&gt;
 *           &lt;element name="BasicMetadata" type="{http://www.movielabs.com/schema/md/v2.3/md}BasicMetadata-type"/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="ContentID" use="required" type="{http://www.movielabs.com/schema/md/v2.3/md}ContentID-type" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Audiovisual-type", propOrder = {
    "type",
    "subType",
    "presentationID",
    "playableSequenceID",
    "playableSequence",
    "contentID",
    "basicMetadata"
})
public class AudiovisualType {

    @XmlElement(name = "Type", required = true)
    protected String type;
    @XmlElement(name = "SubType")
    protected List<String> subType;
    @XmlElement(name = "PresentationID")
    @XmlSchemaType(name = "anyURI")
    protected String presentationID;
    @XmlElement(name = "PlayableSequenceID")
    @XmlSchemaType(name = "anyURI")
    protected String playableSequenceID;
    @XmlElement(name = "PlayableSequence")
    protected PlayableSequenceType playableSequence;
    @XmlElement(name = "ContentID")
    @XmlSchemaType(name = "anyURI")
    protected String contentID;
    @XmlElement(name = "BasicMetadata")
    protected BasicMetadataType basicMetadata;
    @XmlAttribute(name = "ContentID", required = true)
    protected String contentIDAttribute;

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the subType property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the subType property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSubType().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getSubType() {
        if (subType == null) {
            subType = new ArrayList<String>();
        }
        return this.subType;
    }

    /**
     * Gets the value of the presentationID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPresentationID() {
        return presentationID;
    }

    /**
     * Sets the value of the presentationID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPresentationID(String value) {
        this.presentationID = value;
    }

    /**
     * Gets the value of the playableSequenceID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlayableSequenceID() {
        return playableSequenceID;
    }

    /**
     * Sets the value of the playableSequenceID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlayableSequenceID(String value) {
        this.playableSequenceID = value;
    }

    /**
     * Gets the value of the playableSequence property.
     * 
     * @return
     *     possible object is
     *     {@link PlayableSequenceType }
     *     
     */
    public PlayableSequenceType getPlayableSequence() {
        return playableSequence;
    }

    /**
     * Sets the value of the playableSequence property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlayableSequenceType }
     *     
     */
    public void setPlayableSequence(PlayableSequenceType value) {
        this.playableSequence = value;
    }

    /**
     * Gets the value of the contentID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContentID() {
        return contentID;
    }

    /**
     * Sets the value of the contentID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContentID(String value) {
        this.contentID = value;
    }

    /**
     * Gets the value of the basicMetadata property.
     * 
     * @return
     *     possible object is
     *     {@link BasicMetadataType }
     *     
     */
    public BasicMetadataType getBasicMetadata() {
        return basicMetadata;
    }

    /**
     * Sets the value of the basicMetadata property.
     * 
     * @param value
     *     allowed object is
     *     {@link BasicMetadataType }
     *     
     */
    public void setBasicMetadata(BasicMetadataType value) {
        this.basicMetadata = value;
    }

    /**
     * Gets the value of the contentIDAttribute property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContentIDAttribute() {
        return contentIDAttribute;
    }

    /**
     * Sets the value of the contentIDAttribute property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContentIDAttribute(String value) {
        this.contentIDAttribute = value;
    }

}
