//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.08 at 03:02:05 PM PST 
//


package com.wb.nextgen.manifest.schema.v1_4;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import com.wb.nextgen.md.schema.v2_3.BasicMetadataType;
import com.wb.nextgen.md.schema.v2_3.RegionType;


/**
 * <p>Java class for Experience-type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Experience-type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;choice minOccurs="0"&gt;
 *           &lt;element name="Language" type="{http://www.w3.org/2001/XMLSchema}language" maxOccurs="unbounded"/&gt;
 *           &lt;element name="ExcludedLanguage" type="{http://www.w3.org/2001/XMLSchema}language" maxOccurs="unbounded"/&gt;
 *         &lt;/choice&gt;
 *         &lt;choice minOccurs="0"&gt;
 *           &lt;element name="Region" type="{http://www.movielabs.com/schema/md/v2.3/md}Region-type" maxOccurs="unbounded"/&gt;
 *           &lt;element name="ExcludedRegion" type="{http://www.movielabs.com/schema/md/v2.3/md}Region-type" maxOccurs="unbounded"/&gt;
 *         &lt;/choice&gt;
 *         &lt;choice minOccurs="0"&gt;
 *           &lt;element name="ContentID" type="{http://www.movielabs.com/schema/md/v2.3/md}ContentID-type"/&gt;
 *           &lt;element name="BasicMetadata" type="{http://www.movielabs.com/schema/md/v2.3/md}BasicMetadata-type"/&gt;
 *         &lt;/choice&gt;
 *         &lt;element name="Audiovisual" type="{http://www.movielabs.com/schema/manifest/v1.4/manifest}Audiovisual-type" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="App" type="{http://www.movielabs.com/schema/manifest/v1.4/manifest}ExperienceApp-type" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="Gallery" type="{http://www.movielabs.com/schema/manifest/v1.4/manifest}Gallery-type" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="PictureGroupID" type="{http://www.movielabs.com/schema/manifest/v1.4/manifest}PictureGroupID-type" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="TextGroupID" type="{http://www.movielabs.com/schema/manifest/v1.4/manifest}TextGroupID-type" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="TimedSequenceID" type="{http://www.movielabs.com/schema/manifest/v1.4/manifest}TimedSequenceID-type" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="ExperienceChild" type="{http://www.movielabs.com/schema/manifest/v1.4/manifest}ExperienceChild-type" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attGroup ref="{http://www.movielabs.com/schema/manifest/v1.4/manifest}ExperienceAttributes-type"/&gt;
 *       &lt;attribute name="updateNum" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Experience-type", propOrder = {
    "language",
    "excludedLanguage",
    "region",
    "excludedRegion",
    "contentID",
    "basicMetadata",
    "audiovisual",
    "app",
    "gallery",
    "pictureGroupID",
    "textGroupID",
    "timedSequenceID",
    "experienceChild"
})
public class ExperienceType {

    @XmlElement(name = "Language")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "language")
    protected List<String> language;
    @XmlElement(name = "ExcludedLanguage")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "language")
    protected List<String> excludedLanguage;
    @XmlElement(name = "Region")
    protected List<RegionType> region;
    @XmlElement(name = "ExcludedRegion")
    protected List<RegionType> excludedRegion;
    @XmlElement(name = "ContentID")
    @XmlSchemaType(name = "anyURI")
    protected String contentID;
    @XmlElement(name = "BasicMetadata")
    protected BasicMetadataType basicMetadata;
    @XmlElement(name = "Audiovisual")
    protected List<AudiovisualType> audiovisual;
    @XmlElement(name = "App")
    protected List<ExperienceAppType> app;
    @XmlElement(name = "Gallery")
    protected List<GalleryType> gallery;
    @XmlElement(name = "PictureGroupID")
    @XmlSchemaType(name = "anyURI")
    protected List<String> pictureGroupID;
    @XmlElement(name = "TextGroupID")
    @XmlSchemaType(name = "anyURI")
    protected List<String> textGroupID;
    @XmlElement(name = "TimedSequenceID")
    @XmlSchemaType(name = "anyURI")
    protected List<String> timedSequenceID;
    @XmlElement(name = "ExperienceChild")
    protected List<ExperienceChildType> experienceChild;
    @XmlAttribute(name = "updateNum")
    protected BigInteger updateNum;
    @XmlAttribute(name = "ExperienceID")
    protected String experienceID;
    @XmlAttribute(name = "version", required = true)
    protected String version;

    /**
     * Gets the value of the language property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the language property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLanguage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getLanguage() {
        if (language == null) {
            language = new ArrayList<String>();
        }
        return this.language;
    }

    /**
     * Gets the value of the excludedLanguage property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the excludedLanguage property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExcludedLanguage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getExcludedLanguage() {
        if (excludedLanguage == null) {
            excludedLanguage = new ArrayList<String>();
        }
        return this.excludedLanguage;
    }

    /**
     * Gets the value of the region property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the region property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRegion().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RegionType }
     * 
     * 
     */
    public List<RegionType> getRegion() {
        if (region == null) {
            region = new ArrayList<RegionType>();
        }
        return this.region;
    }

    /**
     * Gets the value of the excludedRegion property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the excludedRegion property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExcludedRegion().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RegionType }
     * 
     * 
     */
    public List<RegionType> getExcludedRegion() {
        if (excludedRegion == null) {
            excludedRegion = new ArrayList<RegionType>();
        }
        return this.excludedRegion;
    }

    /**
     * Gets the value of the contentID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContentID() {
        return contentID;
    }

    /**
     * Sets the value of the contentID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContentID(String value) {
        this.contentID = value;
    }

    /**
     * Gets the value of the basicMetadata property.
     * 
     * @return
     *     possible object is
     *     {@link BasicMetadataType }
     *     
     */
    public BasicMetadataType getBasicMetadata() {
        return basicMetadata;
    }

    /**
     * Sets the value of the basicMetadata property.
     * 
     * @param value
     *     allowed object is
     *     {@link BasicMetadataType }
     *     
     */
    public void setBasicMetadata(BasicMetadataType value) {
        this.basicMetadata = value;
    }

    /**
     * Gets the value of the audiovisual property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the audiovisual property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAudiovisual().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AudiovisualType }
     * 
     * 
     */
    public List<AudiovisualType> getAudiovisual() {
        if (audiovisual == null) {
            audiovisual = new ArrayList<AudiovisualType>();
        }
        return this.audiovisual;
    }

    /**
     * Gets the value of the app property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the app property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getApp().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ExperienceAppType }
     * 
     * 
     */
    public List<ExperienceAppType> getApp() {
        if (app == null) {
            app = new ArrayList<ExperienceAppType>();
        }
        return this.app;
    }

    /**
     * Gets the value of the gallery property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the gallery property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGallery().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GalleryType }
     * 
     * 
     */
    public List<GalleryType> getGallery() {
        if (gallery == null) {
            gallery = new ArrayList<GalleryType>();
        }
        return this.gallery;
    }

    /**
     * Gets the value of the pictureGroupID property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the pictureGroupID property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPictureGroupID().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getPictureGroupID() {
        if (pictureGroupID == null) {
            pictureGroupID = new ArrayList<String>();
        }
        return this.pictureGroupID;
    }

    /**
     * Gets the value of the textGroupID property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the textGroupID property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTextGroupID().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getTextGroupID() {
        if (textGroupID == null) {
            textGroupID = new ArrayList<String>();
        }
        return this.textGroupID;
    }

    /**
     * Gets the value of the timedSequenceID property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the timedSequenceID property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTimedSequenceID().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getTimedSequenceID() {
        if (timedSequenceID == null) {
            timedSequenceID = new ArrayList<String>();
        }
        return this.timedSequenceID;
    }

    /**
     * Gets the value of the experienceChild property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the experienceChild property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExperienceChild().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ExperienceChildType }
     * 
     * 
     */
    public List<ExperienceChildType> getExperienceChild() {
        if (experienceChild == null) {
            experienceChild = new ArrayList<ExperienceChildType>();
        }
        return this.experienceChild;
    }

    /**
     * Gets the value of the updateNum property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getUpdateNum() {
        return updateNum;
    }

    /**
     * Sets the value of the updateNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setUpdateNum(BigInteger value) {
        this.updateNum = value;
    }

    /**
     * Gets the value of the experienceID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExperienceID() {
        return experienceID;
    }

    /**
     * Sets the value of the experienceID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExperienceID(String value) {
        this.experienceID = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

}
