//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.08 at 03:02:05 PM PST 
//


package com.wb.nextgen.manifest.schema.v1_4;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import com.wb.nextgen.md.schema.v2_3.ContentSequenceInfoType;


/**
 * <p>Java class for ExperienceChild-type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ExperienceChild-type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Relationship" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="SequenceInfo" type="{http://www.movielabs.com/schema/md/v2.3/md}ContentSequenceInfo-type" minOccurs="0"/&gt;
 *         &lt;element name="ExperienceID" type="{http://www.movielabs.com/schema/manifest/v1.4/manifest}ExperienceID-type"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExperienceChild-type", propOrder = {
    "relationship",
    "sequenceInfo",
    "experienceID"
})
public class ExperienceChildType {

    @XmlElement(name = "Relationship", required = true)
    protected String relationship;
    @XmlElement(name = "SequenceInfo")
    protected ContentSequenceInfoType sequenceInfo;
    @XmlElement(name = "ExperienceID", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String experienceID;

    /**
     * Gets the value of the relationship property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRelationship() {
        return relationship;
    }

    /**
     * Sets the value of the relationship property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRelationship(String value) {
        this.relationship = value;
    }

    /**
     * Gets the value of the sequenceInfo property.
     * 
     * @return
     *     possible object is
     *     {@link ContentSequenceInfoType }
     *     
     */
    public ContentSequenceInfoType getSequenceInfo() {
        return sequenceInfo;
    }

    /**
     * Sets the value of the sequenceInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContentSequenceInfoType }
     *     
     */
    public void setSequenceInfo(ContentSequenceInfoType value) {
        this.sequenceInfo = value;
    }

    /**
     * Gets the value of the experienceID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExperienceID() {
        return experienceID;
    }

    /**
     * Sets the value of the experienceID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExperienceID(String value) {
        this.experienceID = value;
    }

}
