//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.08 at 03:02:05 PM PST 
//


package com.wb.nextgen.manifest.schema.v1_4;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import com.wb.nextgen.md.schema.v2_3.ContactInfoType;
import com.wb.nextgen.md.schema.v2_3.OrgNameType;


/**
 * <p>Java class for FileDelivery-type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FileDelivery-type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="UpdateNum" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/&gt;
 *         &lt;element name="DeliveryMethod" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="TransferLocation" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/&gt;
 *         &lt;element name="Organization" type="{http://www.movielabs.com/schema/md/v2.3/md}OrgName-type" minOccurs="0"/&gt;
 *         &lt;element name="Contact" type="{http://www.movielabs.com/schema/md/v2.3/md}ContactInfo-type" minOccurs="0"/&gt;
 *         &lt;element name="EstDeliveryDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="OtherInstructions" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FileDelivery-type", propOrder = {
    "updateNum",
    "deliveryMethod",
    "transferLocation",
    "organization",
    "contact",
    "estDeliveryDate",
    "otherInstructions"
})
public class FileDeliveryType {

    @XmlElement(name = "UpdateNum")
    protected Object updateNum;
    @XmlElement(name = "DeliveryMethod", required = true)
    protected String deliveryMethod;
    @XmlElement(name = "TransferLocation")
    @XmlSchemaType(name = "anyURI")
    protected String transferLocation;
    @XmlElement(name = "Organization")
    protected OrgNameType organization;
    @XmlElement(name = "Contact")
    protected ContactInfoType contact;
    @XmlElement(name = "EstDeliveryDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar estDeliveryDate;
    @XmlElement(name = "OtherInstructions")
    protected String otherInstructions;

    /**
     * Gets the value of the updateNum property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getUpdateNum() {
        return updateNum;
    }

    /**
     * Sets the value of the updateNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setUpdateNum(Object value) {
        this.updateNum = value;
    }

    /**
     * Gets the value of the deliveryMethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeliveryMethod() {
        return deliveryMethod;
    }

    /**
     * Sets the value of the deliveryMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeliveryMethod(String value) {
        this.deliveryMethod = value;
    }

    /**
     * Gets the value of the transferLocation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransferLocation() {
        return transferLocation;
    }

    /**
     * Sets the value of the transferLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransferLocation(String value) {
        this.transferLocation = value;
    }

    /**
     * Gets the value of the organization property.
     * 
     * @return
     *     possible object is
     *     {@link OrgNameType }
     *     
     */
    public OrgNameType getOrganization() {
        return organization;
    }

    /**
     * Sets the value of the organization property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrgNameType }
     *     
     */
    public void setOrganization(OrgNameType value) {
        this.organization = value;
    }

    /**
     * Gets the value of the contact property.
     * 
     * @return
     *     possible object is
     *     {@link ContactInfoType }
     *     
     */
    public ContactInfoType getContact() {
        return contact;
    }

    /**
     * Sets the value of the contact property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContactInfoType }
     *     
     */
    public void setContact(ContactInfoType value) {
        this.contact = value;
    }

    /**
     * Gets the value of the estDeliveryDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEstDeliveryDate() {
        return estDeliveryDate;
    }

    /**
     * Sets the value of the estDeliveryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEstDeliveryDate(XMLGregorianCalendar value) {
        this.estDeliveryDate = value;
    }

    /**
     * Gets the value of the otherInstructions property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOtherInstructions() {
        return otherInstructions;
    }

    /**
     * Sets the value of the otherInstructions property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOtherInstructions(String value) {
        this.otherInstructions = value;
    }

}
