//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.08 at 03:02:05 PM PST 
//


package com.wb.nextgen.manifest.schema.v1_4;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import com.wb.nextgen.md.schema.v2_3.ContainerMetadataType;
import com.wb.nextgen.md.schema.v2_3.ContentIdentifierType;
import com.wb.nextgen.md.schema.v2_3.HashType;


/**
 * <p>Java class for FileInfo-type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FileInfo-type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Location" type="{http://www.movielabs.com/schema/manifest/v1.4/manifest}Location-type"/&gt;
 *         &lt;element name="Identifier" type="{http://www.movielabs.com/schema/md/v2.3/md}ContentIdentifier-type" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="FileVersion" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/&gt;
 *         &lt;element name="FiileDate" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;union memberTypes=" {http://www.w3.org/2001/XMLSchema}date {http://www.w3.org/2001/XMLSchema}dateTime"&gt;
 *             &lt;/union&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Type"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="manifest"/&gt;
 *               &lt;enumeration value="metadata"/&gt;
 *               &lt;enumeration value="media"/&gt;
 *               &lt;enumeration value="transaction"/&gt;
 *               &lt;enumeration value="ancillary"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Length" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/&gt;
 *         &lt;element name="Hash" type="{http://www.movielabs.com/schema/md/v2.3/md}Hash-type" minOccurs="0"/&gt;
 *         &lt;element name="MIMEType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="WrapperFormat" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ContainerMetadata" type="{http://www.movielabs.com/schema/md/v2.3/md}ContainerMetadata-type" minOccurs="0"/&gt;
 *         &lt;element name="Delivery" type="{http://www.movielabs.com/schema/manifest/v1.4/manifest}FileDelivery-type" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FileInfo-type", propOrder = {
    "location",
    "identifier",
    "fileVersion",
    "fiileDate",
    "type",
    "length",
    "hash",
    "mimeType",
    "wrapperFormat",
    "containerMetadata",
    "delivery"
})
public class FileInfoType {

    @XmlElement(name = "Location", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String location;
    @XmlElement(name = "Identifier")
    protected List<ContentIdentifierType> identifier;
    @XmlElement(name = "FileVersion")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger fileVersion;
    @XmlElement(name = "FiileDate")
    protected String fiileDate;
    @XmlElement(name = "Type", required = true)
    protected String type;
    @XmlElement(name = "Length")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger length;
    @XmlElement(name = "Hash")
    protected HashType hash;
    @XmlElement(name = "MIMEType")
    protected String mimeType;
    @XmlElement(name = "WrapperFormat")
    protected String wrapperFormat;
    @XmlElement(name = "ContainerMetadata")
    protected ContainerMetadataType containerMetadata;
    @XmlElement(name = "Delivery")
    protected FileDeliveryType delivery;

    /**
     * Gets the value of the location property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocation() {
        return location;
    }

    /**
     * Sets the value of the location property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocation(String value) {
        this.location = value;
    }

    /**
     * Gets the value of the identifier property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the identifier property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIdentifier().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ContentIdentifierType }
     * 
     * 
     */
    public List<ContentIdentifierType> getIdentifier() {
        if (identifier == null) {
            identifier = new ArrayList<ContentIdentifierType>();
        }
        return this.identifier;
    }

    /**
     * Gets the value of the fileVersion property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFileVersion() {
        return fileVersion;
    }

    /**
     * Sets the value of the fileVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFileVersion(BigInteger value) {
        this.fileVersion = value;
    }

    /**
     * Gets the value of the fiileDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFiileDate() {
        return fiileDate;
    }

    /**
     * Sets the value of the fiileDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFiileDate(String value) {
        this.fiileDate = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the length property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLength() {
        return length;
    }

    /**
     * Sets the value of the length property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLength(BigInteger value) {
        this.length = value;
    }

    /**
     * Gets the value of the hash property.
     * 
     * @return
     *     possible object is
     *     {@link HashType }
     *     
     */
    public HashType getHash() {
        return hash;
    }

    /**
     * Sets the value of the hash property.
     * 
     * @param value
     *     allowed object is
     *     {@link HashType }
     *     
     */
    public void setHash(HashType value) {
        this.hash = value;
    }

    /**
     * Gets the value of the mimeType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMIMEType() {
        return mimeType;
    }

    /**
     * Sets the value of the mimeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMIMEType(String value) {
        this.mimeType = value;
    }

    /**
     * Gets the value of the wrapperFormat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWrapperFormat() {
        return wrapperFormat;
    }

    /**
     * Sets the value of the wrapperFormat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWrapperFormat(String value) {
        this.wrapperFormat = value;
    }

    /**
     * Gets the value of the containerMetadata property.
     * 
     * @return
     *     possible object is
     *     {@link ContainerMetadataType }
     *     
     */
    public ContainerMetadataType getContainerMetadata() {
        return containerMetadata;
    }

    /**
     * Sets the value of the containerMetadata property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContainerMetadataType }
     *     
     */
    public void setContainerMetadata(ContainerMetadataType value) {
        this.containerMetadata = value;
    }

    /**
     * Gets the value of the delivery property.
     * 
     * @return
     *     possible object is
     *     {@link FileDeliveryType }
     *     
     */
    public FileDeliveryType getDelivery() {
        return delivery;
    }

    /**
     * Sets the value of the delivery property.
     * 
     * @param value
     *     allowed object is
     *     {@link FileDeliveryType }
     *     
     */
    public void setDelivery(FileDeliveryType value) {
        this.delivery = value;
    }

}
