//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.08 at 03:02:05 PM PST 
//


package com.wb.nextgen.manifest.schema.v1_4;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MediaManifestEditAdd-type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MediaManifestEditAdd-type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Compatibility" type="{http://www.movielabs.com/schema/manifest/v1.4/manifest}Compatibility-type" minOccurs="0"/&gt;
 *         &lt;element name="Inventory" type="{http://www.movielabs.com/schema/manifest/v1.4/manifest}Inventory-type" minOccurs="0"/&gt;
 *         &lt;element name="Presentations" type="{http://www.movielabs.com/schema/manifest/v1.4/manifest}PresentationList-type" minOccurs="0"/&gt;
 *         &lt;element name="PlayableSequences" type="{http://www.movielabs.com/schema/manifest/v1.4/manifest}PlayableSequenceList-type" minOccurs="0"/&gt;
 *         &lt;element name="PictureGroups" type="{http://www.movielabs.com/schema/manifest/v1.4/manifest}PictureGroupList-type" minOccurs="0"/&gt;
 *         &lt;element name="AppGroups" type="{http://www.movielabs.com/schema/manifest/v1.4/manifest}AppGroupList-type" minOccurs="0"/&gt;
 *         &lt;element name="Metadata" type="{http://www.movielabs.com/schema/manifest/v1.4/manifest}InventoryMetadata-type" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="TextObject" type="{http://www.movielabs.com/schema/manifest/v1.4/manifest}TextObjectID-type" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="TextGroup" type="{http://www.movielabs.com/schema/manifest/v1.4/manifest}TextGroup-type" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="TextGroups" type="{http://www.movielabs.com/schema/manifest/v1.4/manifest}TextGroupList-type" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="TimedEventSequence" type="{http://www.movielabs.com/schema/manifest/v1.4/manifest}TimedEventSequence-type" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="Experiences" type="{http://www.movielabs.com/schema/manifest/v1.4/manifest}ExperienceList-type" minOccurs="0"/&gt;
 *         &lt;element name="ALIDExperienceMaps" type="{http://www.movielabs.com/schema/manifest/v1.4/manifest}ALIDExperienceMapList-type" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MediaManifestEditAdd-type", propOrder = {
    "compatibility",
    "inventory",
    "presentations",
    "playableSequences",
    "pictureGroups",
    "appGroups",
    "metadata",
    "textObject",
    "textGroup",
    "textGroups",
    "timedEventSequence",
    "experiences",
    "alidExperienceMaps"
})
public class MediaManifestEditAddType {

    @XmlElement(name = "Compatibility")
    protected CompatibilityType compatibility;
    @XmlElement(name = "Inventory")
    protected InventoryType inventory;
    @XmlElement(name = "Presentations")
    protected PresentationListType presentations;
    @XmlElement(name = "PlayableSequences")
    protected PlayableSequenceListType playableSequences;
    @XmlElement(name = "PictureGroups")
    protected PictureGroupListType pictureGroups;
    @XmlElement(name = "AppGroups")
    protected AppGroupListType appGroups;
    @XmlElement(name = "Metadata")
    protected List<InventoryMetadataType> metadata;
    @XmlElement(name = "TextObject")
    @XmlSchemaType(name = "anyURI")
    protected List<String> textObject;
    @XmlElement(name = "TextGroup")
    protected List<TextGroupType> textGroup;
    @XmlElement(name = "TextGroups")
    protected List<TextGroupListType> textGroups;
    @XmlElement(name = "TimedEventSequence")
    protected List<TimedEventSequenceType> timedEventSequence;
    @XmlElement(name = "Experiences")
    protected ExperienceListType experiences;
    @XmlElement(name = "ALIDExperienceMaps")
    protected ALIDExperienceMapListType alidExperienceMaps;

    /**
     * Gets the value of the compatibility property.
     * 
     * @return
     *     possible object is
     *     {@link CompatibilityType }
     *     
     */
    public CompatibilityType getCompatibility() {
        return compatibility;
    }

    /**
     * Sets the value of the compatibility property.
     * 
     * @param value
     *     allowed object is
     *     {@link CompatibilityType }
     *     
     */
    public void setCompatibility(CompatibilityType value) {
        this.compatibility = value;
    }

    /**
     * Gets the value of the inventory property.
     * 
     * @return
     *     possible object is
     *     {@link InventoryType }
     *     
     */
    public InventoryType getInventory() {
        return inventory;
    }

    /**
     * Sets the value of the inventory property.
     * 
     * @param value
     *     allowed object is
     *     {@link InventoryType }
     *     
     */
    public void setInventory(InventoryType value) {
        this.inventory = value;
    }

    /**
     * Gets the value of the presentations property.
     * 
     * @return
     *     possible object is
     *     {@link PresentationListType }
     *     
     */
    public PresentationListType getPresentations() {
        return presentations;
    }

    /**
     * Sets the value of the presentations property.
     * 
     * @param value
     *     allowed object is
     *     {@link PresentationListType }
     *     
     */
    public void setPresentations(PresentationListType value) {
        this.presentations = value;
    }

    /**
     * Gets the value of the playableSequences property.
     * 
     * @return
     *     possible object is
     *     {@link PlayableSequenceListType }
     *     
     */
    public PlayableSequenceListType getPlayableSequences() {
        return playableSequences;
    }

    /**
     * Sets the value of the playableSequences property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlayableSequenceListType }
     *     
     */
    public void setPlayableSequences(PlayableSequenceListType value) {
        this.playableSequences = value;
    }

    /**
     * Gets the value of the pictureGroups property.
     * 
     * @return
     *     possible object is
     *     {@link PictureGroupListType }
     *     
     */
    public PictureGroupListType getPictureGroups() {
        return pictureGroups;
    }

    /**
     * Sets the value of the pictureGroups property.
     * 
     * @param value
     *     allowed object is
     *     {@link PictureGroupListType }
     *     
     */
    public void setPictureGroups(PictureGroupListType value) {
        this.pictureGroups = value;
    }

    /**
     * Gets the value of the appGroups property.
     * 
     * @return
     *     possible object is
     *     {@link AppGroupListType }
     *     
     */
    public AppGroupListType getAppGroups() {
        return appGroups;
    }

    /**
     * Sets the value of the appGroups property.
     * 
     * @param value
     *     allowed object is
     *     {@link AppGroupListType }
     *     
     */
    public void setAppGroups(AppGroupListType value) {
        this.appGroups = value;
    }

    /**
     * Gets the value of the metadata property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the metadata property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMetadata().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InventoryMetadataType }
     * 
     * 
     */
    public List<InventoryMetadataType> getMetadata() {
        if (metadata == null) {
            metadata = new ArrayList<InventoryMetadataType>();
        }
        return this.metadata;
    }

    /**
     * Gets the value of the textObject property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the textObject property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTextObject().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getTextObject() {
        if (textObject == null) {
            textObject = new ArrayList<String>();
        }
        return this.textObject;
    }

    /**
     * Gets the value of the textGroup property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the textGroup property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTextGroup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TextGroupType }
     * 
     * 
     */
    public List<TextGroupType> getTextGroup() {
        if (textGroup == null) {
            textGroup = new ArrayList<TextGroupType>();
        }
        return this.textGroup;
    }

    /**
     * Gets the value of the textGroups property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the textGroups property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTextGroups().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TextGroupListType }
     * 
     * 
     */
    public List<TextGroupListType> getTextGroups() {
        if (textGroups == null) {
            textGroups = new ArrayList<TextGroupListType>();
        }
        return this.textGroups;
    }

    /**
     * Gets the value of the timedEventSequence property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the timedEventSequence property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTimedEventSequence().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TimedEventSequenceType }
     * 
     * 
     */
    public List<TimedEventSequenceType> getTimedEventSequence() {
        if (timedEventSequence == null) {
            timedEventSequence = new ArrayList<TimedEventSequenceType>();
        }
        return this.timedEventSequence;
    }

    /**
     * Gets the value of the experiences property.
     * 
     * @return
     *     possible object is
     *     {@link ExperienceListType }
     *     
     */
    public ExperienceListType getExperiences() {
        return experiences;
    }

    /**
     * Sets the value of the experiences property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExperienceListType }
     *     
     */
    public void setExperiences(ExperienceListType value) {
        this.experiences = value;
    }

    /**
     * Gets the value of the alidExperienceMaps property.
     * 
     * @return
     *     possible object is
     *     {@link ALIDExperienceMapListType }
     *     
     */
    public ALIDExperienceMapListType getALIDExperienceMaps() {
        return alidExperienceMaps;
    }

    /**
     * Sets the value of the alidExperienceMaps property.
     * 
     * @param value
     *     allowed object is
     *     {@link ALIDExperienceMapListType }
     *     
     */
    public void setALIDExperienceMaps(ALIDExperienceMapListType value) {
        this.alidExperienceMaps = value;
    }

}
