//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.08 at 03:02:05 PM PST 
//


package com.wb.nextgen.manifest.schema.v1_4;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MediaManifest-type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MediaManifest-type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Compatibility" type="{http://www.movielabs.com/schema/manifest/v1.4/manifest}Compatibility-type"/&gt;
 *         &lt;element name="Inventory" type="{http://www.movielabs.com/schema/manifest/v1.4/manifest}Inventory-type"/&gt;
 *         &lt;element name="Presentations" type="{http://www.movielabs.com/schema/manifest/v1.4/manifest}PresentationList-type"/&gt;
 *         &lt;element name="PlayableSequences" type="{http://www.movielabs.com/schema/manifest/v1.4/manifest}PlayableSequenceList-type" minOccurs="0"/&gt;
 *         &lt;element name="PictureGroups" type="{http://www.movielabs.com/schema/manifest/v1.4/manifest}PictureGroupList-type" minOccurs="0"/&gt;
 *         &lt;element name="AppGroups" type="{http://www.movielabs.com/schema/manifest/v1.4/manifest}AppGroupList-type" minOccurs="0"/&gt;
 *         &lt;element name="TextGroups" type="{http://www.movielabs.com/schema/manifest/v1.4/manifest}TextGroupList-type" minOccurs="0"/&gt;
 *         &lt;element name="Experiences" type="{http://www.movielabs.com/schema/manifest/v1.4/manifest}ExperienceList-type"/&gt;
 *         &lt;element name="TimedEventSequences" type="{http://www.movielabs.com/schema/manifest/v1.4/manifest}TimedEventSequenceList-type" minOccurs="0"/&gt;
 *         &lt;element name="ALIDExperienceMaps" type="{http://www.movielabs.com/schema/manifest/v1.4/manifest}ALIDExperienceMapList-type" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="ManifestID" type="{http://www.movielabs.com/schema/md/v2.3/md}id-type" /&gt;
 *       &lt;attribute name="updateNum" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *       &lt;attribute name="ExtraVersionReference" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="updateDeliveryType" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MediaManifest-type", propOrder = {
    "compatibility",
    "inventory",
    "presentations",
    "playableSequences",
    "pictureGroups",
    "appGroups",
    "textGroups",
    "experiences",
    "timedEventSequences",
    "alidExperienceMaps"
})
public class MediaManifestType {

    @XmlElement(name = "Compatibility", required = true)
    protected CompatibilityType compatibility;
    @XmlElement(name = "Inventory", required = true)
    protected InventoryType inventory;
    @XmlElement(name = "Presentations", required = true)
    protected PresentationListType presentations;
    @XmlElement(name = "PlayableSequences")
    protected PlayableSequenceListType playableSequences;
    @XmlElement(name = "PictureGroups")
    protected PictureGroupListType pictureGroups;
    @XmlElement(name = "AppGroups")
    protected AppGroupListType appGroups;
    @XmlElement(name = "TextGroups")
    protected TextGroupListType textGroups;
    @XmlElement(name = "Experiences", required = true)
    protected ExperienceListType experiences;
    @XmlElement(name = "TimedEventSequences")
    protected TimedEventSequenceListType timedEventSequences;
    @XmlElement(name = "ALIDExperienceMaps")
    protected ALIDExperienceMapListType alidExperienceMaps;
    @XmlAttribute(name = "ManifestID")
    protected String manifestID;
    @XmlAttribute(name = "updateNum")
    protected BigInteger updateNum;
    @XmlAttribute(name = "ExtraVersionReference")
    protected String extraVersionReference;
    @XmlAttribute(name = "updateDeliveryType")
    protected String updateDeliveryType;

    /**
     * Gets the value of the compatibility property.
     * 
     * @return
     *     possible object is
     *     {@link CompatibilityType }
     *     
     */
    public CompatibilityType getCompatibility() {
        return compatibility;
    }

    /**
     * Sets the value of the compatibility property.
     * 
     * @param value
     *     allowed object is
     *     {@link CompatibilityType }
     *     
     */
    public void setCompatibility(CompatibilityType value) {
        this.compatibility = value;
    }

    /**
     * Gets the value of the inventory property.
     * 
     * @return
     *     possible object is
     *     {@link InventoryType }
     *     
     */
    public InventoryType getInventory() {
        return inventory;
    }

    /**
     * Sets the value of the inventory property.
     * 
     * @param value
     *     allowed object is
     *     {@link InventoryType }
     *     
     */
    public void setInventory(InventoryType value) {
        this.inventory = value;
    }

    /**
     * Gets the value of the presentations property.
     * 
     * @return
     *     possible object is
     *     {@link PresentationListType }
     *     
     */
    public PresentationListType getPresentations() {
        return presentations;
    }

    /**
     * Sets the value of the presentations property.
     * 
     * @param value
     *     allowed object is
     *     {@link PresentationListType }
     *     
     */
    public void setPresentations(PresentationListType value) {
        this.presentations = value;
    }

    /**
     * Gets the value of the playableSequences property.
     * 
     * @return
     *     possible object is
     *     {@link PlayableSequenceListType }
     *     
     */
    public PlayableSequenceListType getPlayableSequences() {
        return playableSequences;
    }

    /**
     * Sets the value of the playableSequences property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlayableSequenceListType }
     *     
     */
    public void setPlayableSequences(PlayableSequenceListType value) {
        this.playableSequences = value;
    }

    /**
     * Gets the value of the pictureGroups property.
     * 
     * @return
     *     possible object is
     *     {@link PictureGroupListType }
     *     
     */
    public PictureGroupListType getPictureGroups() {
        return pictureGroups;
    }

    /**
     * Sets the value of the pictureGroups property.
     * 
     * @param value
     *     allowed object is
     *     {@link PictureGroupListType }
     *     
     */
    public void setPictureGroups(PictureGroupListType value) {
        this.pictureGroups = value;
    }

    /**
     * Gets the value of the appGroups property.
     * 
     * @return
     *     possible object is
     *     {@link AppGroupListType }
     *     
     */
    public AppGroupListType getAppGroups() {
        return appGroups;
    }

    /**
     * Sets the value of the appGroups property.
     * 
     * @param value
     *     allowed object is
     *     {@link AppGroupListType }
     *     
     */
    public void setAppGroups(AppGroupListType value) {
        this.appGroups = value;
    }

    /**
     * Gets the value of the textGroups property.
     * 
     * @return
     *     possible object is
     *     {@link TextGroupListType }
     *     
     */
    public TextGroupListType getTextGroups() {
        return textGroups;
    }

    /**
     * Sets the value of the textGroups property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextGroupListType }
     *     
     */
    public void setTextGroups(TextGroupListType value) {
        this.textGroups = value;
    }

    /**
     * Gets the value of the experiences property.
     * 
     * @return
     *     possible object is
     *     {@link ExperienceListType }
     *     
     */
    public ExperienceListType getExperiences() {
        return experiences;
    }

    /**
     * Sets the value of the experiences property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExperienceListType }
     *     
     */
    public void setExperiences(ExperienceListType value) {
        this.experiences = value;
    }

    /**
     * Gets the value of the timedEventSequences property.
     * 
     * @return
     *     possible object is
     *     {@link TimedEventSequenceListType }
     *     
     */
    public TimedEventSequenceListType getTimedEventSequences() {
        return timedEventSequences;
    }

    /**
     * Sets the value of the timedEventSequences property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimedEventSequenceListType }
     *     
     */
    public void setTimedEventSequences(TimedEventSequenceListType value) {
        this.timedEventSequences = value;
    }

    /**
     * Gets the value of the alidExperienceMaps property.
     * 
     * @return
     *     possible object is
     *     {@link ALIDExperienceMapListType }
     *     
     */
    public ALIDExperienceMapListType getALIDExperienceMaps() {
        return alidExperienceMaps;
    }

    /**
     * Sets the value of the alidExperienceMaps property.
     * 
     * @param value
     *     allowed object is
     *     {@link ALIDExperienceMapListType }
     *     
     */
    public void setALIDExperienceMaps(ALIDExperienceMapListType value) {
        this.alidExperienceMaps = value;
    }

    /**
     * Gets the value of the manifestID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getManifestID() {
        return manifestID;
    }

    /**
     * Sets the value of the manifestID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setManifestID(String value) {
        this.manifestID = value;
    }

    /**
     * Gets the value of the updateNum property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getUpdateNum() {
        return updateNum;
    }

    /**
     * Sets the value of the updateNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setUpdateNum(BigInteger value) {
        this.updateNum = value;
    }

    /**
     * Gets the value of the extraVersionReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExtraVersionReference() {
        return extraVersionReference;
    }

    /**
     * Sets the value of the extraVersionReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExtraVersionReference(String value) {
        this.extraVersionReference = value;
    }

    /**
     * Gets the value of the updateDeliveryType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUpdateDeliveryType() {
        return updateDeliveryType;
    }

    /**
     * Sets the value of the updateDeliveryType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUpdateDeliveryType(String value) {
        this.updateDeliveryType = value;
    }

}
