//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.08 at 03:02:05 PM PST 
//


package com.wb.nextgen.manifest.schema.v1_4;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.wb.nextgen.manifest.schema.v1_4 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _MediaInventory_QNAME = new QName("http://www.movielabs.com/schema/manifest/v1.4/manifest", "MediaInventory");
    private final static QName _MediaPresentation_QNAME = new QName("http://www.movielabs.com/schema/manifest/v1.4/manifest", "MediaPresentation");
    private final static QName _MediaPresentationManifest_QNAME = new QName("http://www.movielabs.com/schema/manifest/v1.4/manifest", "MediaPresentationManifest");
    private final static QName _MediaManifest_QNAME = new QName("http://www.movielabs.com/schema/manifest/v1.4/manifest", "MediaManifest");
    private final static QName _MediaManifestEdit_QNAME = new QName("http://www.movielabs.com/schema/manifest/v1.4/manifest", "MediaManifestEdit");
    private final static QName _FileManifest_QNAME = new QName("http://www.movielabs.com/schema/manifest/v1.4/manifest", "FileManifest");
    private final static QName _FileDeleteManifest_QNAME = new QName("http://www.movielabs.com/schema/manifest/v1.4/manifest", "FileDeleteManifest");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.wb.nextgen.manifest.schema.v1_4
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EventPeriodType }
     * 
     */
    public EventPeriodType createEventPeriodType() {
        return new EventPeriodType();
    }

    /**
     * Create an instance of {@link EventLocationType }
     * 
     */
    public EventLocationType createEventLocationType() {
        return new EventLocationType();
    }

    /**
     * Create an instance of {@link EventLocationOtherCoordinateType }
     * 
     */
    public EventLocationOtherCoordinateType createEventLocationOtherCoordinateType() {
        return new EventLocationOtherCoordinateType();
    }

    /**
     * Create an instance of {@link TimedEventType }
     * 
     */
    public TimedEventType createTimedEventType() {
        return new TimedEventType();
    }

    /**
     * Create an instance of {@link ALIDExperienceMapType }
     * 
     */
    public ALIDExperienceMapType createALIDExperienceMapType() {
        return new ALIDExperienceMapType();
    }

    /**
     * Create an instance of {@link GalleryType }
     * 
     */
    public GalleryType createGalleryType() {
        return new GalleryType();
    }

    /**
     * Create an instance of {@link ExperienceAppType }
     * 
     */
    public ExperienceAppType createExperienceAppType() {
        return new ExperienceAppType();
    }

    /**
     * Create an instance of {@link PlayableSequenceListType }
     * 
     */
    public PlayableSequenceListType createPlayableSequenceListType() {
        return new PlayableSequenceListType();
    }

    /**
     * Create an instance of {@link PictureType }
     * 
     */
    public PictureType createPictureType() {
        return new PictureType();
    }

    /**
     * Create an instance of {@link ChapterType }
     * 
     */
    public ChapterType createChapterType() {
        return new ChapterType();
    }

    /**
     * Create an instance of {@link AncillaryTrackReferenceType }
     * 
     */
    public AncillaryTrackReferenceType createAncillaryTrackReferenceType() {
        return new AncillaryTrackReferenceType();
    }

    /**
     * Create an instance of {@link SubtitleTrackReferenceType }
     * 
     */
    public SubtitleTrackReferenceType createSubtitleTrackReferenceType() {
        return new SubtitleTrackReferenceType();
    }

    /**
     * Create an instance of {@link AudioTrackReferenceType }
     * 
     */
    public AudioTrackReferenceType createAudioTrackReferenceType() {
        return new AudioTrackReferenceType();
    }

    /**
     * Create an instance of {@link VideoTrackReferenceType }
     * 
     */
    public VideoTrackReferenceType createVideoTrackReferenceType() {
        return new VideoTrackReferenceType();
    }

    /**
     * Create an instance of {@link InventoryTextObjectType }
     * 
     */
    public InventoryTextObjectType createInventoryTextObjectType() {
        return new InventoryTextObjectType();
    }

    /**
     * Create an instance of {@link InventoryMetadataType }
     * 
     */
    public InventoryMetadataType createInventoryMetadataType() {
        return new InventoryMetadataType();
    }

    /**
     * Create an instance of {@link InventoryImageType }
     * 
     */
    public InventoryImageType createInventoryImageType() {
        return new InventoryImageType();
    }

    /**
     * Create an instance of {@link MediaProfileType }
     * 
     */
    public MediaProfileType createMediaProfileType() {
        return new MediaProfileType();
    }

    /**
     * Create an instance of {@link PresentationType }
     * 
     */
    public PresentationType createPresentationType() {
        return new PresentationType();
    }

    /**
     * Create an instance of {@link InventoryType }
     * 
     */
    public InventoryType createInventoryType() {
        return new InventoryType();
    }

    /**
     * Create an instance of {@link PresentationManifestType }
     * 
     */
    public PresentationManifestType createPresentationManifestType() {
        return new PresentationManifestType();
    }

    /**
     * Create an instance of {@link MediaManifestType }
     * 
     */
    public MediaManifestType createMediaManifestType() {
        return new MediaManifestType();
    }

    /**
     * Create an instance of {@link MediaManifestEditType }
     * 
     */
    public MediaManifestEditType createMediaManifestEditType() {
        return new MediaManifestEditType();
    }

    /**
     * Create an instance of {@link FileManifestType }
     * 
     */
    public FileManifestType createFileManifestType() {
        return new FileManifestType();
    }

    /**
     * Create an instance of {@link FileDeleteManifestType }
     * 
     */
    public FileDeleteManifestType createFileDeleteManifestType() {
        return new FileDeleteManifestType();
    }

    /**
     * Create an instance of {@link OtherIDType }
     * 
     */
    public OtherIDType createOtherIDType() {
        return new OtherIDType();
    }

    /**
     * Create an instance of {@link TimecodeType }
     * 
     */
    public TimecodeType createTimecodeType() {
        return new TimecodeType();
    }

    /**
     * Create an instance of {@link ContainerReferenceType }
     * 
     */
    public ContainerReferenceType createContainerReferenceType() {
        return new ContainerReferenceType();
    }

    /**
     * Create an instance of {@link AudiovisualClipRefType }
     * 
     */
    public AudiovisualClipRefType createAudiovisualClipRefType() {
        return new AudiovisualClipRefType();
    }

    /**
     * Create an instance of {@link AudioClipRefType }
     * 
     */
    public AudioClipRefType createAudioClipRefType() {
        return new AudioClipRefType();
    }

    /**
     * Create an instance of {@link ImageClipRefType }
     * 
     */
    public ImageClipRefType createImageClipRefType() {
        return new ImageClipRefType();
    }

    /**
     * Create an instance of {@link InventoryAudioType }
     * 
     */
    public InventoryAudioType createInventoryAudioType() {
        return new InventoryAudioType();
    }

    /**
     * Create an instance of {@link InventoryVideoType }
     * 
     */
    public InventoryVideoType createInventoryVideoType() {
        return new InventoryVideoType();
    }

    /**
     * Create an instance of {@link InventorySubtitleType }
     * 
     */
    public InventorySubtitleType createInventorySubtitleType() {
        return new InventorySubtitleType();
    }

    /**
     * Create an instance of {@link InventoryAncillaryType }
     * 
     */
    public InventoryAncillaryType createInventoryAncillaryType() {
        return new InventoryAncillaryType();
    }

    /**
     * Create an instance of {@link InventoryInteractiveType }
     * 
     */
    public InventoryInteractiveType createInventoryInteractiveType() {
        return new InventoryInteractiveType();
    }

    /**
     * Create an instance of {@link InventoryMetadataLocalizedPairType }
     * 
     */
    public InventoryMetadataLocalizedPairType createInventoryMetadataLocalizedPairType() {
        return new InventoryMetadataLocalizedPairType();
    }

    /**
     * Create an instance of {@link InventoryMetadataAliasType }
     * 
     */
    public InventoryMetadataAliasType createInventoryMetadataAliasType() {
        return new InventoryMetadataAliasType();
    }

    /**
     * Create an instance of {@link PresentationLanguagePairType }
     * 
     */
    public PresentationLanguagePairType createPresentationLanguagePairType() {
        return new PresentationLanguagePairType();
    }

    /**
     * Create an instance of {@link TrackMetadataType }
     * 
     */
    public TrackMetadataType createTrackMetadataType() {
        return new TrackMetadataType();
    }

    /**
     * Create an instance of {@link PresentationListType }
     * 
     */
    public PresentationListType createPresentationListType() {
        return new PresentationListType();
    }

    /**
     * Create an instance of {@link ChapterListType }
     * 
     */
    public ChapterListType createChapterListType() {
        return new ChapterListType();
    }

    /**
     * Create an instance of {@link InteractiveTrackReferenceType }
     * 
     */
    public InteractiveTrackReferenceType createInteractiveTrackReferenceType() {
        return new InteractiveTrackReferenceType();
    }

    /**
     * Create an instance of {@link AppGroupType }
     * 
     */
    public AppGroupType createAppGroupType() {
        return new AppGroupType();
    }

    /**
     * Create an instance of {@link AppGroupListType }
     * 
     */
    public AppGroupListType createAppGroupListType() {
        return new AppGroupListType();
    }

    /**
     * Create an instance of {@link PictureGroupType }
     * 
     */
    public PictureGroupType createPictureGroupType() {
        return new PictureGroupType();
    }

    /**
     * Create an instance of {@link PictureGroupListType }
     * 
     */
    public PictureGroupListType createPictureGroupListType() {
        return new PictureGroupListType();
    }

    /**
     * Create an instance of {@link TextGroupType }
     * 
     */
    public TextGroupType createTextGroupType() {
        return new TextGroupType();
    }

    /**
     * Create an instance of {@link TextGroupListType }
     * 
     */
    public TextGroupListType createTextGroupListType() {
        return new TextGroupListType();
    }

    /**
     * Create an instance of {@link PlayableSequenceType }
     * 
     */
    public PlayableSequenceType createPlayableSequenceType() {
        return new PlayableSequenceType();
    }

    /**
     * Create an instance of {@link CompatibilityType }
     * 
     */
    public CompatibilityType createCompatibilityType() {
        return new CompatibilityType();
    }

    /**
     * Create an instance of {@link AudiovisualType }
     * 
     */
    public AudiovisualType createAudiovisualType() {
        return new AudiovisualType();
    }

    /**
     * Create an instance of {@link ExperienceChildType }
     * 
     */
    public ExperienceChildType createExperienceChildType() {
        return new ExperienceChildType();
    }

    /**
     * Create an instance of {@link ExperienceType }
     * 
     */
    public ExperienceType createExperienceType() {
        return new ExperienceType();
    }

    /**
     * Create an instance of {@link ExperienceListType }
     * 
     */
    public ExperienceListType createExperienceListType() {
        return new ExperienceListType();
    }

    /**
     * Create an instance of {@link ALIDExperienceMapListType }
     * 
     */
    public ALIDExperienceMapListType createALIDExperienceMapListType() {
        return new ALIDExperienceMapListType();
    }

    /**
     * Create an instance of {@link TimedEventSequenceType }
     * 
     */
    public TimedEventSequenceType createTimedEventSequenceType() {
        return new TimedEventSequenceType();
    }

    /**
     * Create an instance of {@link TimedEventSequenceListType }
     * 
     */
    public TimedEventSequenceListType createTimedEventSequenceListType() {
        return new TimedEventSequenceListType();
    }

    /**
     * Create an instance of {@link EventLocationEarthCoordinateType }
     * 
     */
    public EventLocationEarthCoordinateType createEventLocationEarthCoordinateType() {
        return new EventLocationEarthCoordinateType();
    }

    /**
     * Create an instance of {@link MediaManifestEditLocRefType }
     * 
     */
    public MediaManifestEditLocRefType createMediaManifestEditLocRefType() {
        return new MediaManifestEditLocRefType();
    }

    /**
     * Create an instance of {@link MediaManifestEditAddType }
     * 
     */
    public MediaManifestEditAddType createMediaManifestEditAddType() {
        return new MediaManifestEditAddType();
    }

    /**
     * Create an instance of {@link MediaManifestEditDeleteType }
     * 
     */
    public MediaManifestEditDeleteType createMediaManifestEditDeleteType() {
        return new MediaManifestEditDeleteType();
    }

    /**
     * Create an instance of {@link FileInfoType }
     * 
     */
    public FileInfoType createFileInfoType() {
        return new FileInfoType();
    }

    /**
     * Create an instance of {@link FileManifestInfoType }
     * 
     */
    public FileManifestInfoType createFileManifestInfoType() {
        return new FileManifestInfoType();
    }

    /**
     * Create an instance of {@link FileDeliveryType }
     * 
     */
    public FileDeliveryType createFileDeliveryType() {
        return new FileDeliveryType();
    }

    /**
     * Create an instance of {@link EventPeriodType.Type }
     * 
     */
    public EventPeriodType.Type createEventPeriodTypeType() {
        return new EventPeriodType.Type();
    }

    /**
     * Create an instance of {@link EventPeriodType.FictionalStart }
     * 
     */
    public EventPeriodType.FictionalStart createEventPeriodTypeFictionalStart() {
        return new EventPeriodType.FictionalStart();
    }

    /**
     * Create an instance of {@link EventPeriodType.FictionalEnd }
     * 
     */
    public EventPeriodType.FictionalEnd createEventPeriodTypeFictionalEnd() {
        return new EventPeriodType.FictionalEnd();
    }

    /**
     * Create an instance of {@link EventLocationType.Type }
     * 
     */
    public EventLocationType.Type createEventLocationTypeType() {
        return new EventLocationType.Type();
    }

    /**
     * Create an instance of {@link EventLocationType.EarthCoordinate }
     * 
     */
    public EventLocationType.EarthCoordinate createEventLocationTypeEarthCoordinate() {
        return new EventLocationType.EarthCoordinate();
    }

    /**
     * Create an instance of {@link EventLocationType.OtherCoordinates }
     * 
     */
    public EventLocationType.OtherCoordinates createEventLocationTypeOtherCoordinates() {
        return new EventLocationType.OtherCoordinates();
    }

    /**
     * Create an instance of {@link EventLocationOtherCoordinateType.Coordinate }
     * 
     */
    public EventLocationOtherCoordinateType.Coordinate createEventLocationOtherCoordinateTypeCoordinate() {
        return new EventLocationOtherCoordinateType.Coordinate();
    }

    /**
     * Create an instance of {@link TimedEventType.TextGroupID }
     * 
     */
    public TimedEventType.TextGroupID createTimedEventTypeTextGroupID() {
        return new TimedEventType.TextGroupID();
    }

    /**
     * Create an instance of {@link ALIDExperienceMapType.ExperienceID }
     * 
     */
    public ALIDExperienceMapType.ExperienceID createALIDExperienceMapTypeExperienceID() {
        return new ALIDExperienceMapType.ExperienceID();
    }

    /**
     * Create an instance of {@link GalleryType.GalleryName }
     * 
     */
    public GalleryType.GalleryName createGalleryTypeGalleryName() {
        return new GalleryType.GalleryName();
    }

    /**
     * Create an instance of {@link ExperienceAppType.AppName }
     * 
     */
    public ExperienceAppType.AppName createExperienceAppTypeAppName() {
        return new ExperienceAppType.AppName();
    }

    /**
     * Create an instance of {@link PlayableSequenceListType.PlayableSequence }
     * 
     */
    public PlayableSequenceListType.PlayableSequence createPlayableSequenceListTypePlayableSequence() {
        return new PlayableSequenceListType.PlayableSequence();
    }

    /**
     * Create an instance of {@link PictureType.AlternateText }
     * 
     */
    public PictureType.AlternateText createPictureTypeAlternateText() {
        return new PictureType.AlternateText();
    }

    /**
     * Create an instance of {@link PictureType.Caption }
     * 
     */
    public PictureType.Caption createPictureTypeCaption() {
        return new PictureType.Caption();
    }

    /**
     * Create an instance of {@link ChapterType.DisplayLabel }
     * 
     */
    public ChapterType.DisplayLabel createChapterTypeDisplayLabel() {
        return new ChapterType.DisplayLabel();
    }

    /**
     * Create an instance of {@link ChapterType.ImageID }
     * 
     */
    public ChapterType.ImageID createChapterTypeImageID() {
        return new ChapterType.ImageID();
    }

    /**
     * Create an instance of {@link AncillaryTrackReferenceType.AdaptationSetID }
     * 
     */
    public AncillaryTrackReferenceType.AdaptationSetID createAncillaryTrackReferenceTypeAdaptationSetID() {
        return new AncillaryTrackReferenceType.AdaptationSetID();
    }

    /**
     * Create an instance of {@link SubtitleTrackReferenceType.AdaptationSetID }
     * 
     */
    public SubtitleTrackReferenceType.AdaptationSetID createSubtitleTrackReferenceTypeAdaptationSetID() {
        return new SubtitleTrackReferenceType.AdaptationSetID();
    }

    /**
     * Create an instance of {@link AudioTrackReferenceType.AdaptationSetID }
     * 
     */
    public AudioTrackReferenceType.AdaptationSetID createAudioTrackReferenceTypeAdaptationSetID() {
        return new AudioTrackReferenceType.AdaptationSetID();
    }

    /**
     * Create an instance of {@link VideoTrackReferenceType.AdaptationSetID }
     * 
     */
    public VideoTrackReferenceType.AdaptationSetID createVideoTrackReferenceTypeAdaptationSetID() {
        return new VideoTrackReferenceType.AdaptationSetID();
    }

    /**
     * Create an instance of {@link InventoryTextObjectType.ContainerReference }
     * 
     */
    public InventoryTextObjectType.ContainerReference createInventoryTextObjectTypeContainerReference() {
        return new InventoryTextObjectType.ContainerReference();
    }

    /**
     * Create an instance of {@link InventoryTextObjectType.TextString }
     * 
     */
    public InventoryTextObjectType.TextString createInventoryTextObjectTypeTextString() {
        return new InventoryTextObjectType.TextString();
    }

    /**
     * Create an instance of {@link InventoryMetadataType.ContainerReference }
     * 
     */
    public InventoryMetadataType.ContainerReference createInventoryMetadataTypeContainerReference() {
        return new InventoryMetadataType.ContainerReference();
    }

    /**
     * Create an instance of {@link InventoryImageType.VideoFrameTimecode }
     * 
     */
    public InventoryImageType.VideoFrameTimecode createInventoryImageTypeVideoFrameTimecode() {
        return new InventoryImageType.VideoFrameTimecode();
    }

    /**
     * Create an instance of {@link MediaProfileType.Profile }
     * 
     */
    public MediaProfileType.Profile createMediaProfileTypeProfile() {
        return new MediaProfileType.Profile();
    }

    /**
     * Create an instance of {@link PresentationType.TrackMetadata }
     * 
     */
    public PresentationType.TrackMetadata createPresentationTypeTrackMetadata() {
        return new PresentationType.TrackMetadata();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InventoryType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.movielabs.com/schema/manifest/v1.4/manifest", name = "MediaInventory")
    public JAXBElement<InventoryType> createMediaInventory(InventoryType value) {
        return new JAXBElement<InventoryType>(_MediaInventory_QNAME, InventoryType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PresentationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.movielabs.com/schema/manifest/v1.4/manifest", name = "MediaPresentation")
    public JAXBElement<PresentationType> createMediaPresentation(PresentationType value) {
        return new JAXBElement<PresentationType>(_MediaPresentation_QNAME, PresentationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PresentationManifestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.movielabs.com/schema/manifest/v1.4/manifest", name = "MediaPresentationManifest")
    public JAXBElement<PresentationManifestType> createMediaPresentationManifest(PresentationManifestType value) {
        return new JAXBElement<PresentationManifestType>(_MediaPresentationManifest_QNAME, PresentationManifestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MediaManifestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.movielabs.com/schema/manifest/v1.4/manifest", name = "MediaManifest")
    public JAXBElement<MediaManifestType> createMediaManifest(MediaManifestType value) {
        return new JAXBElement<MediaManifestType>(_MediaManifest_QNAME, MediaManifestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MediaManifestEditType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.movielabs.com/schema/manifest/v1.4/manifest", name = "MediaManifestEdit")
    public JAXBElement<MediaManifestEditType> createMediaManifestEdit(MediaManifestEditType value) {
        return new JAXBElement<MediaManifestEditType>(_MediaManifestEdit_QNAME, MediaManifestEditType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FileManifestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.movielabs.com/schema/manifest/v1.4/manifest", name = "FileManifest")
    public JAXBElement<FileManifestType> createFileManifest(FileManifestType value) {
        return new JAXBElement<FileManifestType>(_FileManifest_QNAME, FileManifestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FileDeleteManifestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.movielabs.com/schema/manifest/v1.4/manifest", name = "FileDeleteManifest")
    public JAXBElement<FileDeleteManifestType> createFileDeleteManifest(FileDeleteManifestType value) {
        return new JAXBElement<FileDeleteManifestType>(_FileDeleteManifest_QNAME, FileDeleteManifestType.class, null, value);
    }

}
