//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.08 at 03:02:05 PM PST 
//


package com.wb.nextgen.manifest.schema.v1_4;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PlayableSequenceList-type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PlayableSequenceList-type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="PlayableSequence" maxOccurs="unbounded"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;extension base="{http://www.movielabs.com/schema/manifest/v1.4/manifest}PlayableSequence-type"&gt;
 *                 &lt;attribute name="PlayableSequenceID" type="{http://www.movielabs.com/schema/manifest/v1.4/manifest}PlayableSequenceID-type" /&gt;
 *               &lt;/extension&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PlayableSequenceList-type", propOrder = {
    "playableSequence"
})
public class PlayableSequenceListType {

    @XmlElement(name = "PlayableSequence", required = true)
    protected List<PlayableSequenceListType.PlayableSequence> playableSequence;

    /**
     * Gets the value of the playableSequence property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the playableSequence property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPlayableSequence().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PlayableSequenceListType.PlayableSequence }
     * 
     * 
     */
    public List<PlayableSequenceListType.PlayableSequence> getPlayableSequence() {
        if (playableSequence == null) {
            playableSequence = new ArrayList<PlayableSequenceListType.PlayableSequence>();
        }
        return this.playableSequence;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;extension base="{http://www.movielabs.com/schema/manifest/v1.4/manifest}PlayableSequence-type"&gt;
     *       &lt;attribute name="PlayableSequenceID" type="{http://www.movielabs.com/schema/manifest/v1.4/manifest}PlayableSequenceID-type" /&gt;
     *     &lt;/extension&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class PlayableSequence
        extends PlayableSequenceType
    {

        @XmlAttribute(name = "PlayableSequenceID")
        protected String playableSequenceID;

        /**
         * Gets the value of the playableSequenceID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPlayableSequenceID() {
            return playableSequenceID;
        }

        /**
         * Sets the value of the playableSequenceID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPlayableSequenceID(String value) {
            this.playableSequenceID = value;
        }

    }

}
